package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 29, 2011 10:07:06 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javadistribute.finalproject.nguyen_kim_shop.models.Products;

/**
 * Catelogies generated by hbm2java
 */
public class Catelogies  implements java.io.Serializable {


     private Integer catelogyId;
     private Catelogies catelogies;
     private String catelogyName;
     private String catelogyImage;
     private String catelogyDescription;
     private Set<Products> productses = new HashSet<Products>(0);
     private Set<Catelogies> catelogieses = new HashSet<Catelogies>(0);
     private Set<Products> productses_1 = new HashSet<Products>(0);
     private Set<Catelogies> catelogieses_1 = new HashSet<Catelogies>(0);

    public Catelogies() {
    }

    public Catelogies(Catelogies catelogies, String catelogyName, String catelogyImage, String catelogyDescription, Set<Products> productses, Set<Catelogies> catelogieses, Set<Products> productses_1, Set<Catelogies> catelogieses_1) {
       this.catelogies = catelogies;
       this.catelogyName = catelogyName;
       this.catelogyImage = catelogyImage;
       this.catelogyDescription = catelogyDescription;
       this.productses = productses;
       this.catelogieses = catelogieses;
       this.productses_1 = productses_1;
       this.catelogieses_1 = catelogieses_1;
    }
   
    public Integer getCatelogyId() {
        return this.catelogyId;
    }
    
    public void setCatelogyId(Integer catelogyId) {
        this.catelogyId = catelogyId;
    }
    public Catelogies getCatelogies() {
        return this.catelogies;
    }
    
    public void setCatelogies(Catelogies catelogies) {
        this.catelogies = catelogies;
    }
    public String getCatelogyName() {
        return this.catelogyName;
    }
    
    public void setCatelogyName(String catelogyName) {
        this.catelogyName = catelogyName;
    }
    public String getCatelogyImage() {
        return this.catelogyImage;
    }
    
    public void setCatelogyImage(String catelogyImage) {
        this.catelogyImage = catelogyImage;
    }
    public String getCatelogyDescription() {
        return this.catelogyDescription;
    }
    
    public void setCatelogyDescription(String catelogyDescription) {
        this.catelogyDescription = catelogyDescription;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }
    public Set<Catelogies> getCatelogieses() {
        return this.catelogieses;
    }
    
    public void setCatelogieses(Set<Catelogies> catelogieses) {
        this.catelogieses = catelogieses;
    }
    public Set<Products> getProductses_1() {
        return this.productses_1;
    }
    
    public void setProductses_1(Set<Products> productses_1) {
        this.productses_1 = productses_1;
    }
    public Set<Catelogies> getCatelogieses_1() {
        return this.catelogieses_1;
    }
    
    public void setCatelogieses_1(Set<Catelogies> catelogieses_1) {
        this.catelogieses_1 = catelogieses_1;
    }




}


