package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 29, 2011 10:07:06 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private Integer customerId;
     private Roles roles;
     private String firstName;
     private String middleName;
     private String lastName;
     private String email;
     private String address;
     private String phone;
     private Date birthday;
     private String username;
     private String password;
     private Set<Orders> orderses = new HashSet<Orders>(0);
     private Set<Orders> orderses_1 = new HashSet<Orders>(0);

    public Customers() {
    }

    public Customers(Roles roles, String firstName, String middleName, String lastName, String email, String address, String phone, Date birthday, String username, String password, Set<Orders> orderses, Set<Orders> orderses_1) {
       this.roles = roles;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.email = email;
       this.address = address;
       this.phone = phone;
       this.birthday = birthday;
       this.username = username;
       this.password = password;
       this.orderses = orderses;
       this.orderses_1 = orderses_1;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }
    public Set<Orders> getOrderses_1() {
        return this.orderses_1;
    }
    
    public void setOrderses_1(Set<Orders> orderses_1) {
        this.orderses_1 = orderses_1;
    }




}


