package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 29, 2011 10:07:06 AM by Hibernate Tools 3.2.1.GA



/**
 * Parameters generated by hbm2java
 */
public class Parameters  implements java.io.Serializable {


     private Integer parameterId;
     private String prameterName;
     private String parameterType;
     private Double parameterValue;

    public Parameters() {
    }

    public Parameters(String prameterName, String parameterType, Double parameterValue) {
       this.prameterName = prameterName;
       this.parameterType = parameterType;
       this.parameterValue = parameterValue;
    }
   
    public Integer getParameterId() {
        return this.parameterId;
    }
    
    public void setParameterId(Integer parameterId) {
        this.parameterId = parameterId;
    }
    public String getPrameterName() {
        return this.prameterName;
    }
    
    public void setPrameterName(String prameterName) {
        this.prameterName = prameterName;
    }
    public String getParameterType() {
        return this.parameterType;
    }
    
    public void setParameterType(String parameterType) {
        this.parameterType = parameterType;
    }
    public Double getParameterValue() {
        return this.parameterValue;
    }
    
    public void setParameterValue(Double parameterValue) {
        this.parameterValue = parameterValue;
    }




}


