package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 28, 2011 10:43:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Discounts generated by hbm2java
 */
public class Discounts  implements java.io.Serializable {


     private Integer discountId;
     private Products products;
     private Double saleOf;
     private Date fromDate;
     private Date toDate;

    public Discounts() {
    }

    public Discounts(Products products, Double saleOf, Date fromDate, Date toDate) {
       this.products = products;
       this.saleOf = saleOf;
       this.fromDate = fromDate;
       this.toDate = toDate;
    }
   
    public Integer getDiscountId() {
        return this.discountId;
    }
    
    public void setDiscountId(Integer discountId) {
        this.discountId = discountId;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Double getSaleOf() {
        return this.saleOf;
    }
    
    public void setSaleOf(Double saleOf) {
        this.saleOf = saleOf;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }




}


