package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 28, 2011 10:43:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer productId;
     private Tags tags;
     private Imagelist imagelist;
     private Status status;
     private Catelogies catelogies;
     private Suppliers suppliers;
     private String productName;
     private String productDescription;
     private String productDetail;
     private Integer productSmallImage;
     private String productFeatures;
     private String productComments;
     private Integer productQuantity;
     private Float productPrice;
     private Set<Discounts> discountses = new HashSet<Discounts>(0);
     private Set<Orderdetails> orderdetailses = new HashSet<Orderdetails>(0);

    public Products() {
    }

    public Products(Tags tags, Imagelist imagelist, Status status, Catelogies catelogies, Suppliers suppliers, String productName, String productDescription, String productDetail, Integer productSmallImage, String productFeatures, String productComments, Integer productQuantity, Float productPrice, Set<Discounts> discountses, Set<Orderdetails> orderdetailses) {
       this.tags = tags;
       this.imagelist = imagelist;
       this.status = status;
       this.catelogies = catelogies;
       this.suppliers = suppliers;
       this.productName = productName;
       this.productDescription = productDescription;
       this.productDetail = productDetail;
       this.productSmallImage = productSmallImage;
       this.productFeatures = productFeatures;
       this.productComments = productComments;
       this.productQuantity = productQuantity;
       this.productPrice = productPrice;
       this.discountses = discountses;
       this.orderdetailses = orderdetailses;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Tags getTags() {
        return this.tags;
    }
    
    public void setTags(Tags tags) {
        this.tags = tags;
    }
    public Imagelist getImagelist() {
        return this.imagelist;
    }
    
    public void setImagelist(Imagelist imagelist) {
        this.imagelist = imagelist;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Catelogies getCatelogies() {
        return this.catelogies;
    }
    
    public void setCatelogies(Catelogies catelogies) {
        this.catelogies = catelogies;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public String getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail;
    }
    public Integer getProductSmallImage() {
        return this.productSmallImage;
    }
    
    public void setProductSmallImage(Integer productSmallImage) {
        this.productSmallImage = productSmallImage;
    }
    public String getProductFeatures() {
        return this.productFeatures;
    }
    
    public void setProductFeatures(String productFeatures) {
        this.productFeatures = productFeatures;
    }
    public String getProductComments() {
        return this.productComments;
    }
    
    public void setProductComments(String productComments) {
        this.productComments = productComments;
    }
    public Integer getProductQuantity() {
        return this.productQuantity;
    }
    
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }
    public Float getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(Float productPrice) {
        this.productPrice = productPrice;
    }
    public Set<Discounts> getDiscountses() {
        return this.discountses;
    }
    
    public void setDiscountses(Set<Discounts> discountses) {
        this.discountses = discountses;
    }
    public Set<Orderdetails> getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set<Orderdetails> orderdetailses) {
        this.orderdetailses = orderdetailses;
    }




}


