package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 28, 2011 10:43:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers  implements java.io.Serializable {


     private Integer suppliersId;
     private String supplierName;
     private String supplierLogo;
     private Set<Products> productses = new HashSet<Products>(0);

    public Suppliers() {
    }

    public Suppliers(String supplierName, String supplierLogo, Set<Products> productses) {
       this.supplierName = supplierName;
       this.supplierLogo = supplierLogo;
       this.productses = productses;
    }
   
    public Integer getSuppliersId() {
        return this.suppliersId;
    }
    
    public void setSuppliersId(Integer suppliersId) {
        this.suppliersId = suppliersId;
    }
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }
    public String getSupplierLogo() {
        return this.supplierLogo;
    }
    
    public void setSupplierLogo(String supplierLogo) {
        this.supplierLogo = supplierLogo;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


