package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 29, 2011 10:07:06 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Imagelist generated by hbm2java
 */
public class Imagelist  implements java.io.Serializable {


     private Integer imageListId;
     private Integer productId;
     private String imageUrl;
     private Set<Products> productses = new HashSet<Products>(0);
     private Set<Products> productses_1 = new HashSet<Products>(0);

    public Imagelist() {
    }

    public Imagelist(Integer productId, String imageUrl, Set<Products> productses, Set<Products> productses_1) {
       this.productId = productId;
       this.imageUrl = imageUrl;
       this.productses = productses;
       this.productses_1 = productses_1;
    }
   
    public Integer getImageListId() {
        return this.imageListId;
    }
    
    public void setImageListId(Integer imageListId) {
        this.imageListId = imageListId;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }
    public Set<Products> getProductses_1() {
        return this.productses_1;
    }
    
    public void setProductses_1(Set<Products> productses_1) {
        this.productses_1 = productses_1;
    }




}


