package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 29, 2011 10:07:06 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer roleId;
     private String roleName;
     private Set<Customers> customerses = new HashSet<Customers>(0);
     private Set<Customers> customerses_1 = new HashSet<Customers>(0);

    public Roles() {
    }

    public Roles(String roleName, Set<Customers> customerses, Set<Customers> customerses_1) {
       this.roleName = roleName;
       this.customerses = customerses;
       this.customerses_1 = customerses_1;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Set<Customers> getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set<Customers> customerses) {
        this.customerses = customerses;
    }
    public Set<Customers> getCustomerses_1() {
        return this.customerses_1;
    }
    
    public void setCustomerses_1(Set<Customers> customerses_1) {
        this.customerses_1 = customerses_1;
    }




}


