package javadistribute.finalproject.nguyen_kim_shop.models;
// Generated Apr 28, 2011 10:43:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags  implements java.io.Serializable {


     private Integer tagId;
     private String tagName;
     private Set<Products> productses = new HashSet<Products>(0);

    public Tags() {
    }

    public Tags(String tagName, Set<Products> productses) {
       this.tagName = tagName;
       this.productses = productses;
    }
   
    public Integer getTagId() {
        return this.tagId;
    }
    
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


